service: serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser
  region: us-east-1
  stage: dev

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: serverless-dev-upload-bucket
      localDir: uploads

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverless-dev-upload-bucket
