service: serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser
  region: us-east-1
  stage: dev
  httpApi:
    cors: true

plugins:
  - serverless-s3-sync
  - serverless-webpack

package:
  individually: true

custom:
  s3Sync:
    - bucketName: serverless-dev-upload-bucket
      localDir: uploads

functions:
  hello:
    handler: lambdas/hello.handler
  getUser:
    handler: lambdas/getUser.handler
    events:
      - httpApi:
          method: GET
          path: /get-user/{id}

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverless-dev-upload-bucket
